[build]
  base = "frontend/"
  publish = "frontend/build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables будут настроены через Netlify UI
[context.production]
  # REACT_APP_API_URL will be set in Netlify dashboard

[context.deploy-preview] 
  # REACT_APP_API_URL will be set in Netlify dashboard

[context.branch-deploy]
  # REACT_APP_API_URL will be set in Netlify dashboard